/**
 * @type {import('./types').Deployment[]}
 */
export const mockDeployments = [
  {
    id: '1',
    title: 'v2.3.1 배포',
    service: 'Auth Service',
    branch: 'feature/auth',
    prTitle: 'feat: OAuth 2.0 구현',
    status: 'scheduled',
    date: '2025-10-20',
    scheduledTime: '14:00',
    prNumber: '#124',
  },
  {
    id: '2',
    title: 'v3.0.0 배포',
    service: 'API Gateway',
    branch: 'main',
    prTitle: 'feat: 대시보드 리디자인',
    status: 'success',
    date: '2025-10-10',
    scheduledTime: '10:30',
    prNumber: '#142',
  },
  {
    id: '3',
    title: 'Hotfix 배포',
    service: '결제 서비스',
    branch: 'hotfix/payment-bug',
    prTitle: 'fix: 결제 오류 수정',
    status: 'failed',
    date: '2025-10-12',
    scheduledTime: '16:45',
    prNumber: '#156',
  },
  {
    id: '4',
    title: 'v2.4.0 배포',
    service: '공지 서비스',
    branch: 'feature/notifications',
    prTitle: 'feat: 실시간 알림 추가',
    status: 'scheduled',
    date: '2025-10-25',
    scheduledTime: '11:00',
    prNumber: '#167',
  },
  {
    id: '5',
    title: 'v1.9.2 배포',
    service: '인사 서비스',
    branch: 'release/1.9.2',
    prTitle: 'feat: 사용자 프로필 개선',
    status: 'success',
    date: '2025-10-14',
    scheduledTime: '09:00',
    prNumber: '#189',
  },
  {
    id: '6',
    title: 'v4.1.0 배포',
    service: 'AI 서비스',
    branch: 'feature/analytics',
    prTitle: 'feat: 분석 대시보드',
    status: 'scheduled',
    date: '2025-10-28',
    scheduledTime: '15:30',
    prNumber: '#201',
  },
  {
    id: '7',
    title: 'v2.2.0 배포',
    service: 'Auth Service',
    branch: 'release/2.2.0',
    prTitle: 'feat: 2FA 인증 추가',
    status: 'success',
    date: '2025-10-08',
    scheduledTime: '15:00',
    prNumber: '#130',
  },
  {
    id: '8',
    title: '긴급 패치',
    service: '결제 서비스',
    branch: 'hotfix/security',
    prTitle: 'fix: 보안 취약점 수정',
    status: 'failed',
    date: '2025-10-09',
    scheduledTime: '22:30',
    prNumber: '#138',
  },
  {
    id: '9',
    title: 'v3.2.0 배포',
    service: '검색 서비스',
    branch: 'feature/search-v3',
    prTitle: 'feat: 고급 검색 기능',
    status: 'scheduled',
    date: '2025-10-20',
    scheduledTime: '16:30',
    prNumber: '#215',
  },
  // 11월 배포 작업
  {
    id: '10',
    title: 'v2.5.0 배포',
    service: 'Auth Service',
    branch: 'release/2.5.0',
    prTitle: 'feat: JWT 토큰 갱신 개선',
    status: 'scheduled',
    date: '2025-11-05',
    scheduledTime: '10:00',
    prNumber: '#245',
  },
  // 11월 6일 긴 제목 배포 작업
  {
    id: '16',
    title: '대규모 마이크로서비스 아키텍처 리팩토링 및 성능 최적화 작업 배포',
    service: 'API Gateway',
    branch: 'feature/architecture-refactor',
    prTitle: 'feat: 마이크로서비스 아키텍처 리팩토링',
    status: 'scheduled',
    date: '2025-11-06',
    scheduledTime: '09:00',
    prNumber: '#325',
  },
  {
    id: '17',
    title: '실시간 데이터 동기화 시스템 구축 및 분산 캐시 메커니즘 개선 배포',
    service: 'AI 서비스',
    branch: 'feature/realtime-sync',
    prTitle: 'feat: 실시간 데이터 동기화 시스템',
    status: 'scheduled',
    date: '2025-11-06',
    scheduledTime: '14:00',
    prNumber: '#338',
  },
  {
    id: '18',
    title:
      '멀티 테넌트 지원을 위한 데이터베이스 샤딩 전략 구현 및 쿼리 최적화 배포',
    service: '결제 서비스',
    branch: 'feature/multi-tenant-sharding',
    prTitle: 'feat: 멀티 테넌트 데이터베이스 샤딩',
    status: 'scheduled',
    date: '2025-11-06',
    scheduledTime: '16:30',
    prNumber: '#341',
  },
  {
    id: '11',
    title: 'v3.1.0 배포',
    service: 'API Gateway',
    branch: 'release/3.1.0',
    prTitle: 'feat: 로드밸런싱 개선',
    status: 'scheduled',
    date: '2025-11-12',
    scheduledTime: '14:00',
    prNumber: '#268',
  },
  {
    id: '12',
    title: 'Hotfix 배포',
    service: '결제 서비스',
    branch: 'hotfix/payment-refund',
    prTitle: 'fix: 환불 처리 오류 수정',
    status: 'scheduled',
    date: '2025-11-15',
    scheduledTime: '11:30',
    prNumber: '#271',
  },
  {
    id: '13',
    title: 'v2.6.0 배포',
    service: '공지 서비스',
    branch: 'release/2.6.0',
    prTitle: 'feat: 알림 설정 기능 추가',
    status: 'scheduled',
    date: '2025-11-18',
    scheduledTime: '09:00',
    prNumber: '#289',
  },
  {
    id: '14',
    title: 'v4.2.0 배포',
    service: 'AI 서비스',
    branch: 'release/4.2.0',
    prTitle: 'feat: 머신러닝 모델 업데이트',
    status: 'scheduled',
    date: '2025-11-22',
    scheduledTime: '16:00',
    prNumber: '#302',
  },
  {
    id: '15',
    title: 'v1.10.0 배포',
    service: '인사 서비스',
    branch: 'release/1.10.0',
    prTitle: 'feat: 급여 계산 로직 개선',
    status: 'scheduled',
    date: '2025-11-25',
    scheduledTime: '13:00',
    prNumber: '#318',
  },
];

/**
 * @type {import('./types').RestrictedPeriod[]}
 */
export const mockRestrictedPeriods = [
  {
    id: 'r1',
    title: '정기 점검',
    description: '시스템 전체 정기 점검 작업',
    startDate: '2025-10-23',
    startTime: '00:00',
    endDate: '2025-10-24',
    endTime: '06:00',
    type: '서버 점검',
  },
  {
    id: 'r2',
    title: 'DB 마이그레이션',
    description: '데이터베이스 스키마 업데이트',
    startDate: '2025-10-26',
    startTime: '22:00',
    endDate: '2025-10-27',
    endTime: '02:00',
    type: 'DB 마이그레이션',
  },
  {
    id: 'r3',
    title: '긴급 보안 패치',
    description: '보안 취약점 긴급 패치 작업',
    startDate: '2025-10-15',
    startTime: '14:00',
    endDate: '2025-10-17',
    endTime: '18:00',
    type: '외부 일정',
    services: ['Auth Service', 'API Gateway'],
  },
  // 11월 작업 금지 기간
  {
    id: 'r4',
    title: '11월 정기 점검',
    description: '월간 정기 점검 작업',
    startDate: '2025-11-01',
    startTime: '02:00',
    endDate: '2025-11-01',
    endTime: '06:00',
    type: '서버 점검',
    services: ['Auth Service', 'API Gateway', '결제 서비스'],
  },
  {
    id: 'r5',
    title: 'DB 스키마 업데이트',
    description: '데이터베이스 스키마 대규모 업데이트',
    startDate: '2025-11-10',
    startTime: '22:00',
    endDate: '2025-11-11',
    endTime: '04:00',
    type: 'DB 마이그레이션',
    services: ['Auth Service', '인사 서비스', '결제 서비스'],
  },
  {
    id: 'r6',
    title: '긴급 보안 업데이트',
    description: '긴급 보안 패치 적용',
    startDate: '2025-11-20',
    startTime: '20:00',
    endDate: '2025-11-21',
    endTime: '02:00',
    type: '외부 일정',
    services: ['API Gateway', '공지 서비스'],
  },
  {
    id: 'r7',
    title: '시스템 재난 복구 훈련',
    description: '재난 복구 시나리오 테스트',
    startDate: '2025-11-28',
    startTime: '10:00',
    endDate: '2025-11-28',
    endTime: '18:00',
    type: '재난 재해',
    services: ['Auth Service', '결제 서비스', 'AI 서비스'],
  },
  // 9월 작업 금지 기간
  {
    id: 'r8',
    title: '9월 정기 점검',
    description: '월간 정기 점검 작업',
    startDate: '2025-09-05',
    startTime: '02:00',
    endDate: '2025-09-05',
    endTime: '06:00',
    type: '서버 점검',
    services: ['Auth Service', 'API Gateway'],
  },
  {
    id: 'r9',
    title: 'DB 백업 및 복구 테스트',
    description: '데이터베이스 백업 시스템 점검',
    startDate: '2025-09-12',
    startTime: '22:00',
    endDate: '2025-09-13',
    endTime: '02:00',
    type: 'DB 마이그레이션',
    services: ['결제 서비스', '인사 서비스'],
  },
  {
    id: 'r10',
    title: '보안 취약점 스캔',
    description: '전체 시스템 보안 점검',
    startDate: '2025-09-18',
    startTime: '20:00',
    endDate: '2025-09-19',
    endTime: '04:00',
    type: '외부 일정',
    services: ['API Gateway', '공지 서비스', 'AI 서비스'],
  },
  {
    id: 'r11',
    title: '서버 업그레이드 작업',
    description: '서버 하드웨어 및 OS 업그레이드',
    startDate: '2025-09-22',
    startTime: '10:00',
    endDate: '2025-09-22',
    endTime: '18:00',
    type: '서버 점검',
    services: ['Auth Service', '결제 서비스'],
  },
  {
    id: 'r12',
    title: '네트워크 인프라 점검',
    description: '네트워크 장비 정기 점검',
    startDate: '2025-09-28',
    startTime: '00:00',
    endDate: '2025-09-28',
    endTime: '08:00',
    type: '외부 일정',
    services: ['API Gateway', '검색 서비스'],
  },
  // 12월 작업 금지 기간
  {
    id: 'r13',
    title: '12월 정기 점검',
    description: '월간 정기 점검 작업',
    startDate: '2025-12-03',
    startTime: '02:00',
    endDate: '2025-12-03',
    endTime: '06:00',
    type: '서버 점검',
    services: ['Auth Service', 'API Gateway', '결제 서비스'],
  },
  {
    id: 'r14',
    title: '연말 데이터 정리 작업',
    description: '연말 데이터 백업 및 아카이빙',
    startDate: '2025-12-10',
    startTime: '22:00',
    endDate: '2025-12-11',
    endTime: '04:00',
    type: 'DB 마이그레이션',
    services: ['인사 서비스', '결제 서비스', 'AI 서비스'],
  },
  {
    id: 'r15',
    title: '보안 감사 작업',
    description: '연말 보안 감사 및 취약점 점검',
    startDate: '2025-12-17',
    startTime: '20:00',
    endDate: '2025-12-18',
    endTime: '02:00',
    type: '외부 일정',
    services: ['Auth Service', 'API Gateway', '공지 서비스'],
  },
  {
    id: 'r16',
    title: '시스템 성능 최적화',
    description: '연말 시스템 성능 점검 및 최적화',
    startDate: '2025-12-23',
    startTime: '10:00',
    endDate: '2025-12-23',
    endTime: '18:00',
    type: '서버 점검',
    services: ['API Gateway', 'AI 서비스'],
  },
  {
    id: 'r17',
    title: '연말 데이터베이스 정리',
    description: '연말 데이터베이스 정리 및 최적화',
    startDate: '2025-12-29',
    startTime: '00:00',
    endDate: '2025-12-30',
    endTime: '06:00',
    type: 'DB 마이그레이션',
    services: ['결제 서비스', '인사 서비스', '검색 서비스'],
  },
];
