export const PATHS = {
  ROOT: '/',
  AUTH: '/auth',
  AUTH_CALLBACK: '/auth/callback',
  HOME: '/home',
  APPROVALS: '/approvals',
  APPROVAL_NEW: '/approval/new',
  APPROVAL_DETAIL: '/approval/:id',
  APPROVAL_EDIT: '/approval/:id/edit',
  SCHEDULE: '/schedule',
  SCHEDULE_BAN_NEW: '/schedule/ban/new',
  TASKS: '/tasks',
  TASK_DETAIL: '/tasks/:id',
  ANALYTICS: '/analytics',
  PROBLEMS: '/problems',
  PROBLEM_NEW: '/problems/new',
};
